imports:
- path: ../hub/fortigate-security-hub.jinja
  name: fortigate-security-hub.jinja
- path: ha-ap-httplb_ilb.jinja
  name: fortigate.jinja
- path: webservers.jinja

resources:
- name: SecurityHub
  type: fortigate-security-hub.jinja
  properties:
    region: europe-west1
    zones:
    - europe-west1-d
    - europe-west1-c
    fgtInstanceType: e2-highcpu-4
    license:
      type: payg
    version: 6.4.2
    hubNetworks:
      internal:
        name: hub-internal
        ipCidrRange: 10.0.0.64/26
      external:
        name: hub-external
        ipCidrRange: 10.0.0.0/26
      hasync:
        name: hub-hasync
        ipCidrRange: 10.0.0.128/26
      mgmt:
        name: hub-mgmt
        ipCidrRange: 10.0.0.192/26
    spokeNetworks:
    - name: tier1
      ipCidrRange: 192.168.1.0/24
    - name: tier2
      ipCidrRange: 192.168.2.0/24
    fwConfig: |
      config firewall vip
        edit "webserv1"
         set mappedip "192.168.1.2"
         set extintf "port1"
         set portforward enable
         set extport 80
         set mappedport 80
        next
      end
      config firewall policy
        edit 1
         set name "allow-any-out"
         set srcintf "port2"
         set dstintf "port1"
         set srcaddr "all"
         set dstaddr "all"
         set action accept
         set schedule "always"
         set service "ALL"
         set utm-status enable
         set ssl-ssh-profile "certificate-inspection"
         set av-profile "default"
         set webfilter-profile "default"
         set application-list "default"
         set logtraffic all
         set nat enable
        next
        edit 2
         set name "http-to-webserv1"
         set srcintf "port1"
         set dstintf "port2"
         set srcaddr "all"
         set dstaddr "webserv1"
         set action accept
         set schedule "always"
         set service "HTTP"
         set utm-status enable
         set ssl-ssh-profile "certificate-inspection"
         set ips-sensor "default"
         set logtraffic all
         set nat enable
        next
        edit 3
         set name "tier1-to-tier2-any"
         set srcintf "port2"
         set dstintf "port2"
         set srcaddr "all"
         set dstaddr "all"
         set action accept
         set schedule "always"
         set service "ALL"
         set utm-status enable
         set ssl-ssh-profile "certificate-inspection"
         set ips-sensor "default"
         set logtraffic all
        next
      end
      config system interface
        edit port1
        set allowaccess probe-reponse
        next
      end

- name: Web Servers
  type: webservers.jinja
  properties:
    region: europe-west1
    zone: europe-west1-d
    networks:
    - name: tier1
    - name: tier2
    dummy: $(ref.SecurityHub.Default_Password)

outputs:
- name: Management_IP
  value: $(ref.SecurityHub.Management_IP)
- name: Default_Password
  value: $(ref.SecurityHub.Default_Password)
- name: Inbound_Service_Address
  value: $(ref.SecurityHub.Inbound_Service_Addresses[0])
